### ISSUE TITLE
Duplicate addresses

### ISSUE THREAD

**Issue by pezholio** [OpenAddressesUK/distiller#15]
Example:

https://alpha.openaddressesuk.org/addresses?postcode=PL13+1AR

Looking at this in the database, it seems they'd been created within a few seconds of one another:

```
> addresses = Address.where(full_address: "ZUTE, BULLER STREET, LOOE, PL13 1AR")
> addresses.first.updated_at
=> Wed, 01 Apr 2015 16:43:30 UTC +00:00
> addresses.last.updated_at
=> Wed, 01 Apr 2015 16:43:33 UTC +00:00
```

I'm putting this down to some rogue instances of Distiller running at the same time, but I'm deleting the dupes and will investigate the cause in a bit more depth

**Comment by pezholio** [comment]
I've isolated this in tests now:

```
threads = []

2.times do
  threads << Thread.new { Distiller::Distil.perform }
end

threads.each { |thr| thr.join }

expect(Address.count).to eq 25
```

```
  1) Distiller::Distil distiller does not create duplicates
     Failure/Error: expect(Address.count).to eq 25
       
       expected: 25
            got: 43
       
       (compared using ==)
     # ./spec/distil_spec.rb:152:in `block (3 levels) in <top (required)>'
```

**Comment by Floppy** [comment]
Unfortunately MongoDB doesn't provide synchronisation locks / transactions I don't think, so we might never be able to completely avoid this if two distillers are running at once.

**Comment by Floppy** [comment]
Though we can minimise it by adjusting the checks in the code perhaps.

**Comment by pezholio** [comment]
Yeah, I think you're right there. I think the solution here might be just to make sure we don't have any overlapping runs.

**Comment by Floppy** [comment]
That too. We could bung a lock record into the database that is checked by the distiller run.

**Comment by pezholio** [comment]
I've now removed the dupes from the live DB, and we have a lock record which *should* stop this from happening again
